services:
  frontend:
    build:
      context: ./ethio-news-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./ethio-news-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DATABASE_HOST: ${DB_HOST}
      DATABASE_PORT: ${DB_PORT}
      DATABASE_USER: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
      DATABASE_NAME: ${DB_DATABASE}
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: ethio_news_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
